### ISSUE TITLE
README.md does not include time of taco train departure

### ISSUE THREAD

**Issue by edsirko** [olicea/pokefacts#4]
This can result in a suboptimal user experience, as users may not know when the taco train leaves on Wednesdays.

**Comment by olicea** [comment]
thanks for the feedback @edsirko 

that I believe falls into the Food realm (@philipslan), what I know is that by default the time is flexible as people might be busy or not as hungry, the location is flexible too, traditionally we go to the same place, but that can change.

**Comment by olicea** [comment]
won't fix
